# this what you want to be the default wiki page
startpage: Welcome_to_Junebug

# server configuration
host: 0.0.0.0
port: 3301

# if you want to have the wiki root running on something other than /
sitepath: /

# database configuration
dbconnection:
#
# sqlite3 configuration
  adapter: sqlite3
  database: junebug.db
#
## postgresql configuration
#  adapter: postgresql
#  database: junebug
#  username:
#  password:
#  socket: /tmp
#
## mysql configuration
#  adapter: mysql
#  database: junebug
#  username:
#  password:
#  host: localhost

# configuring rss
# you should only need to change this is you have an external feed manager like feedburner
feedtitle: Wiki Updates
feedurl: http://localhost:3301
feed: http://localhost:3301/all/feed

